### ISSUE TITLE
Cache for production

### ISSUE THREAD

**Issue by carusogabriel** [BKWLD/laravel-pug#13]
Hello there :wave: 

Can someone please help me in this one: how can I <b>cache</b> compiled files to use in production, to _improve_ `storage` and `performance`?

Thanks :smile:

**Comment by weotch** [comment]
Laravel takes care of that automatically.  The compiled pug files are stored in `storage/framework/views` and will be used on subsequent requests as long as the pug file hasn't changed since the cache was created.  It's as described here: https://laravel.com/docs/5.4/blade#introduction

> In fact, all Blade views are compiled into plain PHP code and cached until they are modified, meaning Blade adds essentially zero overhead to your application.

This package taps into the same subsystem for caching views as blade.
