### ISSUE TITLE
Include something.pug.blade.php not parsing

### ISSUE THREAD

**Issue by SkyaTura** [BKWLD/laravel-pug#16]
I just noticed that if you include a .pug.blade.php file will just write in plain text instead of parse pug.

**Comment by kylekatarnls** [comment]
Why a **.php** would be parsed with pug? It's the same expected behavior as in pugjs:
https://pugjs.org/language/includes.html
Any other file than **.pug** (or the extensions you would add) will be included as plain text.

In order to parse **.php** files with pug, add it with the extension option:
```php
$pug->setOption('extension', array('.pug', '.php'));
```

But such a triple extension seems to me a very confusing way to name your files (you can have html, css and js in a PHP file but nobody will name it foo.css-and-js.html.php). The extension should rely to the the main program that read the file, in this case **something.pug** is clean and quite enough.

**Comment by weotch** [comment]
This should work, if you want to add support within your app.  Add this in your app service provider:

```
app('view')->addExtension('pug.blade.php', 'pug.blade');
``

**Comment by kylekatarnls** [comment]
Hi, I just realize the blade feature is only enable with with the double/triple extension and understand better the problem and took a look at the `addExtensions` @weotch added. Just a doubt:
https://github.com/BKWLD/laravel-pug/blob/master/src/ServiceProvider.php#L144
This shouldn't be:
```php
->addExtension('jade.blade', 'pug.blade')
```
Instead of:
```php
->addExtension('jade.blade', 'jade.blade')
```
It seems there is no `jade.blade` engine registered.
