### ISSUE TITLE
Syntax highlighting in IDEs

### ISSUE THREAD

**Issue by fbcarpinato** [BKWLD/laravel-pug#20]
Can't get the jade/pug syntax with in files like " *.pug,blade.php"

**Comment by kylekatarnls** [comment]
Could you be a bit more specific?

Did you follow the README: https://github.com/BKWLD/laravel-pug/blob/master/README.md

I see a comma in your post: `" *.pug,blade.php"`, it should be all dots: `"*.pug.blade.php"`

**Comment by fbcarpinato** [comment]
I miss writed in the post the file name, the problem is that the jade syntax recognized in the blade files (at least in phpstorm), there is some fix?

**Comment by kylekatarnls** [comment]
Each syntax in your IDE PhpStorm or any else need a plugin to be properly highlighted. Some of them are installed by default. But the all-in-one blade and pug plugin does not exist in PhpStorm until someone created it. My recommandation is to use `.pug` extension because blade and PHP are punctual part in pug templates (the same way you can embed javascript and css in `.html` files does not mean you need to give multiple extensions to your file). This way PhpStorm will understand the main language and just do little mistakes in expressions but it should not be a big deal to work with and the way your IDE understand the file has no impact on the final interpretation.
