### ISSUE TITLE
extend pug.blade

### ISSUE THREAD

**Issue by diegovdc** [BKWLD/laravel-pug#21]
Hello, is it possible to extend a pug.blade file? So that legacy layouts can remain usable, but also extendable.

So as to be able to do something like this:
```
@extends('layouts/admin')
include /cltvo/front/my-pug-mixins.pug

@section('content')
block content
@endsection
```

**Comment by diegovdc** [comment]
Update: I see that it is actually possible, but it turns out that the error was that I had an admin.blade.php and and an admin.pug.blade, and the fact that bod shared the same "first name", `admin`, was the cause of the error, would that be an actual issue?

**Comment by kylekatarnls** [comment]
Hi,

We talk a lot about file extensions in issues. They are the root of many confusion for users. That's why I recommend to follow this best practice:

**Only one extension per file.**

It make sense because you never have multiple languages at the same level, you have 1 main language that embed others. For example, `.html` can embed inline JS and CSS but you never name your file `.css.js.html` you just name it `.html`

Here the right name is `admin.pug` and you should have only one. If you have 2 files, find a relevant difference to give them names like `admin-foo.blade` and `admin-bar.pug`.

**Comment by diegovdc** [comment]
thank you Kyle!
