### ISSUE TITLE
Using @ directives in js mode

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [BKWLD/laravel-pug#68]
How do I use `@error` or `@guest` or `@auth` or things like that in js pug mode?

for example something like this
```
@error('email')
	<span class="invalid-feedback" role="alert">
		<strong>{{ $message }}</strong>
	</span>
@enderror
```

**Comment by matthewjumpsoffbuildings** [comment]
it would be nice to have documented somewhere all the pug js features that map directly to the template control structures laid out here

https://laravel.com/docs/5.8/blade#control-structures

**Comment by kylekatarnls** [comment]
Second example of the README:
https://github.com/BKWLD/laravel-pug#usage

Use `.pug.blade` extension.
And in your case (nothing to escape), the `|` is not needed:
```pug
@error('email')
span.invalid-feedback(role="alert")
	strong=message
@enderror
```

Pug-php is fully documented here: https://phug-lang.com

`@auth` is `if Auth::id()` `@guest` is `if Auth::guest()`

If you use the option `'pugjs' => true` then you will need to share `'userId' => Auth::id()` as a global variable so you can use `if userId` / `if !userId` instead.

The doc of pugjs: https://pugjs.org

Most feature that map directly have the same name too: if, else, elseif, unless, while, break, continue, foreach-empty becomes each-else, switch-case becomes case-when. Indent, remove `@endxx`.

And that's it. Other features are not strictly equivalent, that's why this adapter allow to use both on need.
