### ISSUE TITLE
how do you do a blade interpolation within an attribute?

### ISSUE THREAD

**Issue by hlsmelo** [BKWLD/laravel-pug#91]
I tried in different ways to do the interpolation and I couldn't. no search answered any doubt

example: the code below 

`input(type="text" value="{{ $text_value }}")`

always returns an input with the value "{{ $text_value }}"

**Comment by kylekatarnls** [comment]
It would work only for a `.blade.pug` file, if it's a `.pug` file you can't, but in both case you can just use the Pug style:
```pug
input(type="text" value=text_value)
```

**Comment by hlsmelo** [comment]
> It would work only for a `.blade.pug` file, if it's a `.pug` file you can't, but in both case you can just use the Pug style:
> 
> ```
> input(type="text" value=text_value)
> ```

but the variable is php, even if I set a value like 
`@php
 $text_value='test'
@endphp`
and set it in the input like you said, it doesn't work

**Comment by kylekatarnls** [comment]
I see.

Actually Pug variables are also in PHP when using this package, so for instance, this does work like a charm:
```php
Route::get('/foo', function () {
    return view('dual', ['text_value' => 'abc']);
});
```
dual.blade.pug:
```pug
input(type="text" value=text_value)
```

Loading /foo in browser:
```html
<input type="text" value="abc" />
```

But variable created by blade are created after Pug finish to compile the template. So Pug-php will simply take your file, parse it as Pug code, ignoring completely any Blade code, then it creates an intermediate blade file and then Blade compile it.

So this works too:
```php
@php($text_value='test')
p {{ $text_value }}
<input type="text" value="{{ $text_value }}">
```
But mixing both in a nested way is not possible.

**Comment by kylekatarnls** [comment]
To be more precise about the limitation: we need (for performance reason) to compile only once a template into a PHP file, then this cached PHP file is used to render the view for each HTTP request, so we don't have a re-compile for each user on each page load. This means a code like `input(type="text" value="{{ $text_value }}")` is not turned into `<input type="text" value="{{ $text_value }}">` because the output can actually depends on values/runtime events (for instance when using modules or adding event listeners), so instead it compiles into something like: `<?php render_tag('input', ['type' => "text", 'value' => "{{ \$text_value }}"]); ?>` and Blade won't interpolate anything in a PHP tag like this, so we're quite stuck in the process.

**Comment by kylekatarnls** [comment]
So finally, my recommendation would be to do the maximum in Pug code. The `.blade.pug` is designed to help transition from one to the other, but you can do with Pug anything you are actually doing with Blade, so at the end, you should be able to completely turn your template into a pure `.pug` file (and optionally include pure `.blade` files in it) and that will probably help you to have a cleaner template code easier to be understood by other devs or yourself in the future.

So I would rather get the issue at the root and if you have code that you don't know how to convert from Blade to Pug, that's probably the question to ask first.
